application:
  env: development
  debug: false
  graceful_shutdown_timeout: "30s"

http_server:
  port: 8000
  timeout: "5s"

mysql:
  host: go-backend-clean-arch_mysqldb
  PORT: 3306
  username: admin
  password: 123456
  database: backend_db
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_life_time: 5

redis:
  host: go-backend-clean-arch_redis
  port: 6379
  password: 123456
  db: 0
  dial_timeout: 5
  read_timeout: 5
  write_timeout: 5
  pool_size: 10
  pool_timeout: 15
  idle_check_frequency: 500
